### ISSUE TITLE
Node Plugin for Gradle

### ISSUE THREAD

**Issue by rgoomar** [gbaldeck/vue.kt#1]
Did you consider using the Node plugin for Gradle (https://github.com/srs/gradle-node-plugin) and running your entire build cycle through Gradle? I've only used it in one project previously, but might be nice to have here to hook multiple commands together.

**Comment by gbaldeck** [comment]
I'm sure it can be done, but chose not to focus my time on that. Feel free to fork the repo and do a pull request.
